### PR TITLE
Event order fix and old events for admins

### PR DESCRIPTION
**Pull request by Nesssu**
Now the order of the events is based on the start time of the events and not the order of creation. The old events are not deleted but they are not visible for the normal users. Admins can view old events (if there are any) at the bottom of the home page. Editing, liking and buying tickets are disabled on the old events, so admins can only view and delete them. 

Also, when the editing or deleting of the events is disabled, the buttons were disabled. Changed it so that the buttons are hidden when they can't be used. Makes the EventItem look a little nicer :)

### CODE REVIEW

**Review by jannejjj — COMMENTED** [review]
Couldn't figure out why i was getting the issues i was getting, so i'll wait for others to review/test this to confirm whether or not the issues were on my end or not :D

A couple of comments:
1) Would it be possible to have a "Loading" text displayed while the old events are being loaded?
2) Would it be possible to not show the "show past events" button before the events above have been loaded?

**Comment by Jezerig** [comment]
Tried adding a new event and nothing shows up

**Comment by jannejjj** [comment]
I'm getting an error because of these 2 props:
image

the functions are undefined since their definitions have been removed. Also there's no need to pass them as props, since the toasts are imported separately in eventitem.js :D

**Comment by Nesssu** [comment]
- Fixed the crash that was caused by the toastMessages. 
- Fixed the issue with events without an endDate not been shown
- Added a loading text for the past events (event though it's not visible that well :) )
- Not showing the show past events button while the events are loading. The button is still shown before the events but that is caused by the fact that it takes longer for the events to render that for the button, but I don't think it's a big deal

**Review by Enlarem — APPROVED** [review]
Seems to work well for me. Maybe if you can sort the past event in the opposite way, so we see the most recent passed events first, it would be nice :D

**Comment by Jezerig** [comment]
- Events that only have a start date are not moved into past events when the start date has passed

**Comment by jannejjj** [comment]
See Jesse's comment above. Other than that, seems good :D

**Comment by Nesssu** [comment]
- The order of the past events reversed
- Events without endDate will be shown in the past events the day after the startDate

**Pull request merged**
