### PR TITLE
News page

### PR DESCRIPTION
**Pull request by Jezerig**
Added: 
- News page
- Button for admins to create news posts
- Post creation modal
- Delete button for deleting posts
- Delete post confirmation modal
- Toast messages on creation and deletion
- Commented code

Removed:
- Change language buttons from the top bar

### CODE REVIEW

**Review by jannejjj — APPROVED** [review]
Looks nice and works well!

**Review by Enlarem — COMMENTED** [review]
It nice and very convenient for what we want to do for now. I just want to notice few things I saw when testing : 

- CR are not working when trying to insert some into the description field
- User information is lacking on my front end side, but it might be because of my local data
- The toasts are not working also, but it might be because of the same problem

I think it would be very nice if we could insert CR in the description of the news modal. Maybe instead of the TextField component you could use a Multiline component ?

**Comment by Jezerig** [comment]
> It nice and very convenient for what we want to do for now. I just want to notice few things I saw when testing :
> 
> * CR are not working when trying to insert some into the description field
> * User information is lacking on my front end side, but it might be because of my local data
> * The toasts are not working also, but it might be because of the same problem
> 
> I think it would be very nice if we could insert CR in the description of the news modal. Maybe instead of the TextField component you could use a Multiline component ?

I think you might be missing two of the latest commits for the creator details and the toasts🤔 Also, What is CR?:D

**Comment by Enlarem** [comment]
Ho yeah you are right !! I forgot to pull... It is working now. By CR I meant the '\n' character :grin:

**Comment by Jezerig** [comment]
> Ho yeah you are right !! I forgot to pull... It is working now. By CR I meant the '\n' character 😁

Ok, fixed the issue with the line break The <p> component wasn't displaying it correctly.

**Review by Enlarem — APPROVED** [review]
Works really well now !

**Pull request merged**
