### PR TITLE
Registration and login

### PR DESCRIPTION
**Pull request by Jezerig**
Added:
- Registration and login pages
- JWT auth token in sessionStorage
- Logout working (removes token from sessionStorage)
- Member list can only be viewed if authorized (token in sessionStorage/logged in)
- login button will dissapear when logged in and is replaced by logout button in the top bar
- Added 'register' button to appear in the top bar when not logged in
- My Profile disappears when logged out
- Password hash and salt (bcryptjs)
- isStrongPassword, isEmail when registering

### CODE REVIEW

**Review by jannejjj — COMMENTED** [review]
Looks and works great! I especially love the` whenChanging` approach for register and login. Just gotta remember to add the `SECRET` environment variable to .env on cloud and local machines when this is merged 👌

**Review by jannejjj — APPROVED** [review]

**Comment by jannejjj** [comment]
[402 - Login](https://trello.com/c/wFUQqZ7P/28-402-login)

**Comment by jannejjj** [comment]
[401 - Sign in](https://trello.com/c/nPon4VDD/27-401-sign-in)

**Comment by jannejjj** [comment]
[401 - Sign in](https://trello.com/c/nPon4VDD/27-401-sign-in)

**Comment by jannejjj** [comment]
[403 - Log out](https://trello.com/c/YP1UoEN3/29-403-log-out)

**Comment by jannejjj** [comment]
[410 - Connection token](https://trello.com/c/oIhJWR86/30-410-connection-token)

**Comment by Nesssu** [comment]
Updated the front-end

**Review by mh-lut — APPROVED** [review]

**Pull request merged**
